Fix FinalizedDataModelIsMarkedAsFinalizedInXMLSpec
MetadataConsulting/ModelCataloguePlugin pull request #1176
Opened 2018-04-02 06:59 UTC by Vendetta30

Download the XML of the finalized data model and check the downloaded XML has the finalized data model name. Changes are three files:
**GebConfig**: Added the configuration to download the file and save it a location  
**DataModelPage**: Added the download link.  
**FinalizedDataModelIsMarkedAsFinalizedInXMLSpec**: Testing file

2018-04-02 08:01 UTC, sdelamo requested changes

2018-04-02 08:01 UTC, sdelamo commented on ModelCatalogueCorePluginTestApp/test/functional/GebConfig.groovy
> +        String downloadFilepath = "/home/vijay/"
@Vendetta30 could you wrap this code with : 

```
if ( System.getProperty('downloadFilepath') ) {
String downloadFilePath = System.getProperty('downloadFilepath')
.........
} else {
  driver = { new ChromeDriver() }		
}
```

2018-04-02 08:01 UTC, sdelamo commented on ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/remoteTesting/FinalizedDataModelIsMarkedAsFinalizedInXMLSpec.groovy
>      def 'Examine that finalized data model is marked as finalized in the XML'() {
@Vendetta30 Could you annotate this test with: 

`@IgnoreIf({ !System.getProperty("downloadFilepath") })`

2018-04-02 08:01 UTC, sdelamo commented on ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/remoteTesting/FinalizedDataModelIsMarkedAsFinalizedInXMLSpec.groovy
> +        cancelFile.text.contains(dataModelName)
@Vendetta30 this should check that the status is Finalized in the XML. See attachment

<img width="744" alt="napkin 7 02-04-18 10 01 24 am" src="https://user-images.githubusercontent.com/864788/38188568-cde5200a-365c-11e8-867b-9c45ea23c91c.png">

2018-04-02 09:14 UTC, Vendetta30 commented
@sdelamo 
I did the changes as you suggested, please check and let me know.
https://github.com/MetadataConsulting/ModelCataloguePlugin/commit/7b37d03562a7dd9cbcd6b9901e7388fbb09da72b

2018-04-03 09:48 UTC, sdelamo commented
Thanks @Vendetta30 I have organized the file deletion in the cleanup block and small changes. @davidmilward you can merge this PR.

2018-04-03 09:50 UTC, Vendetta30 commented
@sdelamo 
Thanks, I will take care of it next time.

2018-04-03 12:56 UTC, merged